/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cards/{card_uuid}/card_description": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_uuid: string;
            };
            cookie?: never;
        };
        /** Shows a card description */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    card_uuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description card description found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CardDescription"];
                    };
                };
                /** @description card description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Updates a card description */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    card_uuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CardDescriptionInput"];
                };
            };
            responses: {
                /** @description card description updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CardDescription"];
                    };
                };
                /** @description card description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        /** Creates a card description */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    card_uuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CardDescriptionInput"];
                };
            };
            responses: {
                /** @description card description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CardDescription"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists cards */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description cards listed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"][];
                    };
                };
            };
        };
        put?: never;
        /** Creates a card */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CardInput"];
                };
            };
            responses: {
                /** @description card created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        /** Shows a card */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description card found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description card is draft */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/cards/{card_uuid}/card_description": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_uuid: string;
            };
            cookie?: never;
        };
        /** Shows a card description */
        get: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path: {
                    card_uuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description card description found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerCardDescription"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description card description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/cards/{card_uuid}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_uuid: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attaches a tag to a card */
        post: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path: {
                    card_uuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CardTagInput"];
                };
            };
            responses: {
                /** @description tag already attached (idempotent) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description tag attached */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description tag not found */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/cards/{card_uuid}/tags/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_uuid: string;
                slug: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detaches a tag from a card */
        delete: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path: {
                    card_uuid: string;
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description unknown tag slug (idempotent) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/cards/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists draft cards */
        get: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description draft cards listed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerDraftCard"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/cards/drafts/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        /** Shows a draft card */
        get: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path: {
                    uuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description draft card found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerDraftCard"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description draft card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a card */
        post: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OwnerCardInput"];
                };
            };
            responses: {
                /** @description draft card created without pinyin */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerCard"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description published card without pinyin */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/cards/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Updates a card */
        put: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path: {
                    uuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OwnerCardInput"];
                };
            };
            responses: {
                /** @description card unpublished */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerCard"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a tag */
        post: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TagInput"];
                };
            };
            responses: {
                /** @description tag created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerTag"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_slug}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_slug: string;
            };
            cookie?: never;
        };
        /** Lists cards belonging to a tag */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tag_slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description cards listed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"][];
                    };
                };
                /** @description tag not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists tags */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description tags listed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tag"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Card: {
            uuid: string;
            name: string;
            pinyin: string;
            tags: components["schemas"]["Tag"][];
            card_description: {
                content: string;
            } | null;
        };
        CardDescription: {
            content: string;
        };
        Tag: {
            slug: string;
            name: string;
        };
        OwnerCard: {
            id: number;
            uuid: string;
            name: string;
            pinyin: string;
            /** Format: date-time */
            published_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OwnerDraftCard: {
            id: number;
            uuid: string;
            name: string;
            pinyin: string;
            /** Format: date-time */
            published_at: string | null;
            tags: components["schemas"]["Tag"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OwnerCardDescription: {
            id: number;
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OwnerTag: {
            id: number;
            name: string;
            slug: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CardInput: {
            card: {
                name: string;
                pinyin: string;
            };
        };
        OwnerCardInput: {
            card: {
                name: string;
                pinyin?: string;
                /** Format: date-time */
                published_at?: string | null;
            };
        };
        CardDescriptionInput: {
            card_description: {
                content: string;
            };
        };
        TagInput: {
            tag: {
                name: string;
                slug: string;
            };
        };
        CardTagInput: {
            tag_slug: string;
        };
        Errors: {
            errors: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
